name: Robot-framework.yml

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11  # Define a versão mais recente de Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11  # Usa apenas a versão mais recente de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install robotframework robotframework-pabot robotframework-seleniumlibrary allure-robotframework
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with Robot Framework and generate Allure report
      run: |
        robot --outputdir allure-results Web/tests

    # Instalação do Allure CLI no Windows
    - name: Download Allure CLI for Windows
      run: |
        curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.zip
        tar -xf allure.zip
        setx PATH "%PATH%;D:\\a\\ServeRest-Robot\\ServeRest-Robot\\allure-2.20.1\\bin"  # Adiciona ao PATH do Windows

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report  # Gera o HTML do relatório

    - name: Publish Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
