name: Robot-framework.yml

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install robotframework robotframework-pabot robotframework-seleniumlibrary allure-robotframework
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with Robot Framework and generate Allure report
      run: |
        robot --outputdir allure-results Web/tests  # Executa os testes e gera os resultados para o Allure

    - name: Install Allure CLI
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report  # Gera o HTML do relatório

    - name: Publish Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics